### ISSUE TITLE
Crash IllegalAgrumentException

### ISSUE THREAD

**Issue by the-vindex** [vadis365/Mob-Grinding-Utils#31]
Full log here:
https://gist.githubusercontent.com/the-vindex/83f07a8ab6f393ff02bd2727b110d42c/raw/ab1480fe6e067ce7fde20ab7824f8a58ee1e1db9/gistfile1.txt

Version:   MobGrindingUtils-0.1.8.16

Context: Fans are powered with normal levers, but se below

Beginning of stack trace:

java.lang.IllegalArgumentException: Cannot get property PropertyBool{name=powered, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:203)
	at mob_grinding_utils.tile.TileEntityFan.func_73660_a(TileEntityFan.java:33)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1789)

**Comment by vadis365** [comment]
I have not been able to duplicate this bug and this is the only report of it.
It may be due to other mod's interaction (like Optifine).
Closing for now and will re-open if other reports of the same issue happen.
