### ISSUE TITLE
Running on a server in 1.12 crash

### ISSUE THREAD

**Issue by StoutyAlex** [vadis365/Mob-Grinding-Utils#46]
Running latest forge build of 14.21.1.2396, works okay on client side but 
crashes when installed on server side

`---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.2-99.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 05/07/17 12:31
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from mob_grinding_utils (mob_grinding_utils)
Caused by: net.minecraftforge.fml.common.LoaderException: java.lang.ClassNotFoundException: mob_grinding_utils.ModModels
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:606)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:252)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:147)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:570)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:97)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:335)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:122)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:483)
	at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: mob_grinding_utils.ModModels
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:81)
	... 32 more
Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer@17ae98d7 from coremod FMLCorePlugin
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:262)
	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279)
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176)
	... 38 more
Caused by: java.lang.RuntimeException: Attempted to load class mob_grinding_utils/ModModels for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:62)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:258)
	... 40 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1419467192 bytes (1353 MB) / 1518862336 bytes (1448 MB) up to 4772593664 bytes (4551 MB)
	JVM Flags: 2 total; -Xmx5G -Xms1G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.40 Powered by Forge 14.21.1.2396 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2396-universal.jar) 
	UC	forge{14.21.1.2396} [Minecraft Forge] (forge-1.12-14.21.1.2396-universal.jar) 
	UC	quark{r1.2-99} [Quark] (Quark-r1.2-99.jar) 
	UC	autoreglib{1.3-12} [AutoRegLib] (AutoRegLib-1.3-12.jar) 
	UC	bookshelf{2.0.408} [Bookshelf] (Bookshelf-1.12-2.0.0.408.jar) 
	UC	chesttransporter{2.8.3} [Chest Transporter] (ChestTransporter-1.12-2.8.3.jar) 
	UC	jei{4.7.1.69} [Just Enough Items] (jei_1.12-4.7.1.69.jar) 
	UC	darkutils{${version}} [Dark Utilities] (DarkUtils-1.12-1.6.156.jar) 
	UC	quickleafdecay{1.2.3} [Quick Leaf Decay] (FastLeafDecay-Mod-1.12.jar) 
	UC	gravestone{1.8.4} [Gravestone Mod] (gravestone-1.8.4.jar) 
	UC	ironchest{1.12-7.0.31.818} [Iron Chest] (ironchest-1.12-7.0.31.818.jar) 
	UE	mob_grinding_utils{0.3.0} [mob_grinding_utils] (MobGrindingUtils-0.3.0 (1).jar) 
	UC	oreexcavation{1.4.100} [OreExcavation] (OreExcavation-1.4.100.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.2-99.jar)
  vazkii.quark.base.asm.ClassTransformer
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)`

**Comment by vadis365** [comment]
Hello,
Whoops, looks like I missed a clientside only call to the model loader - fix will uploaded soon.
Thanks for the report.
Cheers,
Me.

**Comment by vadis365** [comment]
Hello,
Version 0.3.1 is now being approved on curse and should fix the model loader event, now it should only be called on the client. Sorry about that. Please let me know if this fixes your issue.
Cheers,
Me.

**Comment by StoutyAlex** [comment]
Hi,
Thanks for the quick fix, all working now!
